### ISSUE TITLE
Exiting a game causes crash

### ISSUE THREAD

**Issue by MRmikimous** [BartoszCichecki/LenovoLegionToolkit#1069]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.17.0

### OS

Windows 11 22H2 Build 22621.2792

### Device

Legion Pro 5 16ARX8

### BIOS version

LPCN42WW

### What's wrong?

After exiting a game "Paragon: The Overprime", Toolkit crashes

### How to reproduce the bug?

Launch "Paragon: The Overprime"
Exit the game
Wait about 5-10 sec for game to fully close
Toolkit crashes

### What is the behavior that you expected?

Toolkit not to crash

### Logs

AppDomain_UnhandledException
=== Exception ===
System.Runtime.InteropServices.COMException (0x80070006): The handle is invalid. (0x80070006 (E_HANDLE))
   at Interop.Kernel32.ProcessWaitHandle..ctor(SafeProcessHandle processHandle)
   at System.Diagnostics.Process.UpdateHasExited()
   at System.Diagnostics.Process.get_HasExited()
   at LenovoLegionToolkit.Lib.AutoListeners.GameAutoListener.<>c.<Process_Exited>b__18_0(Process p)
   at System.Collections.Generic.HashSet`1.RemoveWhere(Predicate`1 match)
   at LenovoLegionToolkit.Lib.AutoListeners.GameAutoListener.Process_Exited(Object o, EventArgs args)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, Boolean timedOut)
   at System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, Boolean timedOut)
   at System.Threading.CompleteWaitThreadPoolWorkItem.CompleteWait()

=== Exception demystified ===
System.Runtime.InteropServices.COMException: The handle is invalid. (0x80070006 (E_HANDLE))
   at new Interop+Kernel32+ProcessWaitHandle(SafeProcessHandle processHandle)
   at void System.Diagnostics.Process.UpdateHasExited()
   at bool System.Diagnostics.Process.get_HasExited()
   at void LenovoLegionToolkit.Lib.AutoListeners.GameAutoListener.Process_Exited(object o, EventArgs args)+(Process p) => { }
   at int System.Collections.Generic.HashSet<T>.RemoveWhere(Predicate<T> match)
   at void LenovoLegionToolkit.Lib.AutoListeners.GameAutoListener.Process_Exited(object o, EventArgs args)
   at void System.Diagnostics.Process.OnExited()
   at void System.Diagnostics.Process.RaiseOnExited()
   at void System.Diagnostics.Process.CompletionCallback(object waitHandleContext, bool wasSignaled)
   at void System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(object state)
   at void System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, bool timedOut)
   at void System.Threading.PortableThreadPool.CompleteWait(RegisteredWaitHandle handle, bool timedOut)
   at void System.Threading.CompleteWaitThreadPoolWorkItem.CompleteWait()

**Comment by BartoszCichecki** [comment]
Fix will be included in next release (soon). Thanks for reporting!
