### ISSUE TITLE
Cannot open after installation: ERROR Sequence contains no elements

### ISSUE THREAD

**Issue by StringKe** [BartoszCichecki/LenovoLegionToolkit#1107]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.18.0

### OS

Windows 11 21H2 22000.856

### Device

Legion R9000P ARX8

### BIOS version

None

### What's wrong?

This error occurs when opening after installation.

### How to reproduce the bug?

1. install
2. open

### What is the behavior that you expected?

Open normally.

### Logs

AppDomain_UnhandledException
=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.System.Management.WMI.Win32.ComputerSystemProduct.ReadAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LenovoLegionToolkit.WPF.App.Main()

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<(string vendor, string name, string version, string identifyingNumber)> LenovoLegionToolkit.Lib.System.Management.WMI+Win32+ComputerSystemProduct.ReadAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at void System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at void System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at void MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at void MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at void System.Windows.Threading.DispatcherOperation.Invoke()
   at void System.Windows.Threading.Dispatcher.ProcessQueue()
   at IntPtr System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at IntPtr MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at object MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at object System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at IntPtr MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at IntPtr MS.Win32.UnsafeNativeMethods.DispatchMessage(in MSG msg)
   at void System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.Run()
   at object System.Windows.Application.RunDispatcher(object ignore)
   at int System.Windows.Application.RunInternal(Window window)
   at int System.Windows.Application.Run()
   at void LenovoLegionToolkit.WPF.App.Main()

**Comment by StringKe** [comment]
all full logs

log_2024_01_06_15_39_11

```
[06/01/2024 15:39:11.244] [1] [App.xaml.cs#69:Application_Startup] Flags: IsTraceEnabled: True, Minimized: False, SkipCompatibilityCheck: False, DisableTrayTooltip: False, AllowAllPowerModesOnBattery: False, ForceDisableRgbKeyboardSupport: False, ForceDisableSpectrumKeyboardSupport: False, ForceDisableLenovoLighting: False, ExperimentalGPUWorkingMode: False, EnableHybridModeAutomation: False
[06/01/2024 15:39:11.245] [1] [App.xaml.cs#283:EnsureSingleInstance] Checking for other instances...
[06/01/2024 15:39:11.253] [1] [LocalizationHelper.cs#151:SetLanguageInternal] Applied culture: en
[06/01/2024 15:39:11.308] [1] [App.xaml.cs#228:Application_DispatcherUnhandledException] Unhandled exception occurred.
=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.System.Management.WMI.Win32.ComputerSystemProduct.ReadAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<(string vendor, string name, string version, string identifyingNumber)> LenovoLegionToolkit.Lib.System.Management.WMI+Win32+ComputerSystemProduct.ReadAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

[06/01/2024 15:39:12.406] [1] [App.xaml.cs#216:AppDomain_UnhandledException] Unhandled exception occurred.
=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.System.Management.WMI.Win32.ComputerSystemProduct.ReadAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LenovoLegionToolkit.WPF.App.Main()

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<(string vendor, string name, string version, string identifyingNumber)> LenovoLegionToolkit.Lib.System.Management.WMI+Win32+ComputerSystemProduct.ReadAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at void System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at void System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at void MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at void MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at void System.Windows.Threading.DispatcherOperation.Invoke()
   at void System.Windows.Threading.Dispatcher.ProcessQueue()
   at IntPtr System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at IntPtr MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at object MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at object System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at IntPtr MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at IntPtr MS.Win32.UnsafeNativeMethods.DispatchMessage(in MSG msg)
   at void System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.Run()
   at object System.Windows.Application.RunDispatcher(object ignore)
   at int System.Windows.Application.RunInternal(Window window)
   at int System.Windows.Application.Run()
   at void LenovoLegionToolkit.WPF.App.Main()
```

error_2024_01_06_15_39_11
```
Application_DispatcherUnhandledException
=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.System.Management.WMI.Win32.ComputerSystemProduct.ReadAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<(string vendor, string name, string version, string identifyingNumber)> LenovoLegionToolkit.Lib.System.Management.WMI+Win32+ComputerSystemProduct.ReadAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
```

error_2024_01_06_15_39_12
```
AppDomain_UnhandledException
=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.System.Management.WMI.Win32.ComputerSystemProduct.ReadAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LenovoLegionToolkit.WPF.App.Main()

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<(string vendor, string name, string version, string identifyingNumber)> LenovoLegionToolkit.Lib.System.Management.WMI+Win32+ComputerSystemProduct.ReadAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformationAsync()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.WPF.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at void System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at void System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at void MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at void MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at void System.Windows.Threading.DispatcherOperation.Invoke()
   at void System.Windows.Threading.Dispatcher.ProcessQueue()
   at IntPtr System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at IntPtr MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at object MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at object System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at IntPtr MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at IntPtr MS.Win32.UnsafeNativeMethods.DispatchMessage(in MSG msg)
   at void System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.Run()
   at object System.Windows.Application.RunDispatcher(object ignore)
   at int System.Windows.Application.RunInternal(Window window)
   at int System.Windows.Application.Run()
   at void LenovoLegionToolkit.WPF.App.Main()


```

**Comment by BartoszCichecki** [comment]
This isn't the prettiest way to handle this, but LLT will crash if it can't read basic information about the device from WMI. Resolve issues with your Windows install and all will be fine.
