### ISSUE TITLE
Bug Report: CPU / GPU dashboard sensors often disappearing intermittently

### ISSUE THREAD

**Issue by Msprg** [BartoszCichecki/LenovoLegionToolkit#1163]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.20.0 build 20240204202718

### OS

Windows 11 Pro for Workstations, 23H2 build 22631.3007

### Device

Legion 5 15IAH7H, machine type 82RB

### BIOS version

J2CN54WW

### What's wrong?

CPU and GPU monitoring in dashboard/sensors often disappear/show as `-`. Usually, the more loaded are the specific components, the more often and for longer they disappear. This happens regardless of the power mode set, but more often on "performance ones" (incl. custom mode).

For example, if CPU is loaded to 100%, it usually disappears for the whole duration of being under load. Tools such as Windows task manager and system informer (formerly process hacker) seem to be reporting values consistently and correctly)
The more the utilization comes down, the more stable LLT readings are, though they are not too stable even on lower components utilization (it's happening right now as I'm just typing this at around 20% of GPU util.)

Issue happens regardless of hybrid/dgpu modes, detached dgpu detection appears to work correctly.

I have not modified anything such as UEFI/BIOS or the GPU firmware. Everything should be stock.

Possibly a bit related to #1117 

See attached screen recording (not recorded at the same time as logging, only for visual illustration) and [LLT log](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14199751/log_2024_02_07_17_51_51.txt). I tried reproducing as many issues as I could during logging.

https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/18015488/36a3b767-2bdd-4b7c-a2c7-1a66a1b13665

### How to reproduce the bug?

Just load the CPU/GPU while looking at LLT's dashboard

### What is the behavior that you expected?

Indicators shouldn't be disappearing.

### Logs

[LLT log](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14199751/log_2024_02_07_17_51_51.txt)

**Comment by BartoszCichecki** [comment]
Good catch, fixed.

**Comment by Msprg** [comment]
Hello and thank you for such a fast fix!

I have tested the build from d89c3f9 and from my short test the fix appears to work flawlessly for the GPU.


Unfortunately, the CPU utilization is still broken for me when CPU is fully loaded, see attached screenshot:
![obrázok](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/18015488/c752ae0d-1d1e-4841-981a-0106d0e5f0ad)


I'm also attaching a [log](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/14202206/log_2024_02_07_22_13_43.txt) from that build (this time produced alongside the screenshot).


You might be interested in this specific excerpt of the log, since it appears to be pretty much the same as the fix you pushed in d89c3f9. I'm however no programmer by any means so you be the judge.

```
[07. 02. 2024 22:13:45.875] [9] [AbstractWmiFeature.cs#47:GetStateAsync] State is Balance [feature=PowerModeFeature]
[07. 02. 2024 22:13:45.879] [1] [AbstractWmiFeature.cs#41:GetStateAsync] Getting state... [feature=OverDriveFeature]
[07. 02. 2024 22:13:45.881] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=FnLockFeature]
[07. 02. 2024 22:13:45.881] [9] [AbstractDriverFeature.cs#46:GetStateAsync] Buffer value: 17096 [feature=FnLockFeature]
[07. 02. 2024 22:13:45.882] [9] [AbstractDriverFeature.cs#52:GetStateAsync] State is Off [feature=FnLockFeature]
[07. 02. 2024 22:13:45.886] [23] [AbstractWmiFeature.cs#47:GetStateAsync] State is Off [feature=OverDriveFeature]
[07. 02. 2024 22:13:45.892] [1] [AbstractWmiFeature.cs#41:GetStateAsync] Getting state... [feature=TouchpadLockFeature]
[07. 02. 2024 22:13:45.897] [1] [AbstractWmiFeature.cs#41:GetStateAsync] Getting state... [feature=WinKeyFeature]
[07. 02. 2024 22:13:45.899] [1] [AbstractRefreshingControl.cs#58:RefreshAsync] Exception when refreshing control. [feature=BatteryNightChargeModeControl]
=== Exception ===
System.NotSupportedException: Specified method is not supported.
   at LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl`1.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

=== Exception demystified ===
System.NotSupportedException: Specified method is not supported.
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl<T>.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

[07. 02. 2024 22:13:45.917] [23] [AbstractWmiFeature.cs#47:GetStateAsync] State is Off [feature=TouchpadLockFeature]
[07. 02. 2024 22:13:45.917] [9] [AbstractWmiFeature.cs#47:GetStateAsync] State is Off [feature=WinKeyFeature]
[07. 02. 2024 22:13:45.917] [32] [SpectrumKeyboardBacklightController.cs#585:GetDeviceHandleAsync] Refreshing handle... [retry=2]
[07. 02. 2024 22:13:45.925] [1] [AbstractRefreshingControl.cs#58:RefreshAsync] Exception when refreshing control. [feature=OneLevelWhiteKeyboardBacklightControl]
=== Exception ===
System.NotSupportedException: Specified method is not supported.
   at LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl`1.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

=== Exception demystified ===
System.NotSupportedException: Specified method is not supported.
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl<T>.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

[07. 02. 2024 22:13:45.925] [1] [AbstractRefreshingControl.cs#58:RefreshAsync] Exception when refreshing control. [feature=PortsBacklightControl]
=== Exception ===
System.NotSupportedException: Specified method is not supported.
   at LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl`1.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

=== Exception demystified ===
System.NotSupportedException: Specified method is not supported.
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl<T>.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

[07. 02. 2024 22:13:45.934] [32] [Power.cs#42:IsAcFitForOc] Mode = 1
[07. 02. 2024 22:13:45.943] [9] [Power.cs#59:IsChargingNormally] Mode = 1
[07. 02. 2024 22:13:45.968] [9] [SpectrumKeyboardBacklightController.cs#585:GetDeviceHandleAsync] Refreshing handle... [retry=3]
[07. 02. 2024 22:13:45.993] [9] [SafePerformanceCounter.cs#48:TryCreateIfNeeded] Creating performance counter. [categoryName=Processor Information, counterName=% Processor Performance, instanceName=_Total]
[07. 02. 2024 22:13:46.031] [32] [SpectrumKeyboardBacklightController.cs#600:GetDeviceHandleAsync] Handle couldn't be refreshed.
[07. 02. 2024 22:13:46.032] [23] [SpectrumKeyboardBacklightController.cs#585:GetDeviceHandleAsync] Refreshing handle... [retry=1]
[07. 02. 2024 22:13:46.037] [23] [AbstractLenovoLightingFeature.cs#39:IsSupportedAsync] Control interface not found [feature=WhiteKeyboardLenovoLightingBacklightFeature]

```

**Comment by BartoszCichecki** [comment]
CPU load is most likely an issue with Windows Performance Counters, so you might try to reset/rebuild them (google instructions). Although some people consistently have issues with them.

**Comment by Msprg** [comment]
I see... Well, I tried resetting them, did not help at all.

Still, thanks for the other fix.

Have a nice day~!
