### ISSUE TITLE
Error at Star the App

### ISSUE THREAD

**Issue by XschlexX** [BartoszCichecki/LenovoLegionToolkit#1281]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.2

### OS

Windows 11 23H2

### Device

Legion 7 IAX7

### BIOS version

K1CN46WW

### What's wrong?

At start the App, they abort with many errors.
[error_2024_05_13_11_44_48.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/15294094/error_2024_05_13_11_44_48.txt)

### How to reproduce the bug?

Start the APP

### What is the behavior that you expected?

Starting the App

### Logs

=== Exception ===
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetBIOSVersionAsync()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformation()
   at LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at LenovoLegionToolkit.App.CheckCompatibilityAsync()
   at LenovoLegionToolkit.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Sequence contains no elements
   at void System.Linq.ThrowHelper.ThrowNoElementsException()
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at async Task<string> LenovoLegionToolkit.Lib.Utils.Compatibility.GetBIOSVersionAsync()
   at async Task<MachineInformation> LenovoLegionToolkit.Lib.Utils.Compatibility.GetMachineInformation()
   at async Task<(bool isCompatible, MachineInformation machineInformation)> LenovoLegionToolkit.Lib.Utils.Compatibility.IsCompatibleAsync()
   at async Task LenovoLegionToolkit.App.CheckCompatibilityAsync()
   at async void LenovoLegionToolkit.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

**Comment by BartoszCichecki** [comment]
This is an issue with WMI on your OS, please fix your OS.

**Comment by XschlexX** [comment]
What is a WMI
________________________________
Von: Bartosz Cichecki ***@***.***>
Gesendet: Monday, May 13, 2024 2:07:49 PM
An: BartoszCichecki/LenovoLegionToolkit ***@***.***>
Cc: XschlexX ***@***.***>; Author ***@***.***>
Betreff: Re: [BartoszCichecki/LenovoLegionToolkit] Error at Star the App (Issue #1281)


This is an issue with WMI on your OS, please fix your OS.

**Comment by XschlexX** [comment]
And how can i fix it?
________________________________
Von: Bartosz Cichecki ***@***.***>
Gesendet: Monday, May 13, 2024 2:17:20 PM
An: BartoszCichecki/LenovoLegionToolkit ***@***.***>
Cc: XschlexX ***@***.***>; Author ***@***.***>
Betreff: Re: [BartoszCichecki/LenovoLegionToolkit] Error at Star the App (Issue #1281)


Windows Management Instrumentation<https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page>

**Comment by XschlexX** [comment]
Can you help me please? I have tried so mach and nothing help.
________________________________
Von: Alexander Schmidt ***@***.***>
Gesendet: Monday, May 13, 2024 2:18:30 PM
An: BartoszCichecki/LenovoLegionToolkit ***@***.***>; BartoszCichecki/LenovoLegionToolkit ***@***.***>
Cc: Author ***@***.***>
Betreff: Re: [BartoszCichecki/LenovoLegionToolkit] Error at Star the App (Issue #1281)

And how can i fix it?
________________________________
Von: Bartosz Cichecki ***@***.***>
Gesendet: Monday, May 13, 2024 2:17:20 PM
An: BartoszCichecki/LenovoLegionToolkit ***@***.***>
Cc: XschlexX ***@***.***>; Author ***@***.***>
Betreff: Re: [BartoszCichecki/LenovoLegionToolkit] Error at Star the App (Issue #1281)


Windows Management Instrumentation<https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page>

**Comment by BartoszCichecki** [comment]
Sorry, I don't do general support here. You can check out the discord server that is linked in the readme.

**Comment by BartoszCichecki** [comment]
Just updated and got the same crash. Hotfix is released now. This is a first, so apologies for scepticism.
