### ISSUE TITLE
Unhandled Exception on Launch

### ISSUE THREAD

**Issue by jeffkk** [BartoszCichecki/LenovoLegionToolkit#1287]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.21.1

### OS

Windows 11 Home 10.0.22631

### Device

Legion 7 Slim 16APH8

### BIOS version

M1CN34WW

### What's wrong?

when attempting to launch a new install of the legion toolkit, i get an unhandled exception error

### How to reproduce the bug?

attempt to launch application

### What is the behavior that you expected?

Application to launch

### Logs

Application_DispatcherUnhandledException
=== Exception ===
System.Management.ManagementException: Call failed: Invalid object . [scope=root\WMI, query=SELECT * FROM LENOVO_GAMEZONE_DATA, methodName=GetSmartFanMode]
 ---> System.Management.ManagementException: Invalid object 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
   at LenovoLegionToolkit.Lib.System.Management.WMI.CallAsync[T](String scope, FormattableString query, String methodName, Dictionary`2 methodParams, Func`2 converter)
   --- End of inner exception stack trace ---
   at LenovoLegionToolkit.Lib.System.Management.WMI.CallAsync[T](String scope, FormattableString query, String methodName, Dictionary`2 methodParams, Func`2 converter)
   at LenovoLegionToolkit.Lib.Features.AbstractWmiFeature`1.GetStateAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.ShouldDisableAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.StopAsync()
   at LenovoLegionToolkit.Lib.Controllers.AIController.StartIfNeededAsync()
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.Management.ManagementException: Call failed: Invalid object . [scope=root\WMI, query=SELECT * FROM LENOVO_GAMEZONE_DATA, methodName=GetSmartFanMode]
   at async Task<T> LenovoLegionToolkit.Lib.System.Management.WMI.CallAsync<T>(string scope, FormattableString query, string methodName, Dictionary<string, object> methodParams, Func<PropertyDataCollection, T> converter)
   at async Task<T> LenovoLegionToolkit.Lib.Features.AbstractWmiFeature<T>.GetStateAsync()
   at async Task<bool> LenovoLegionToolkit.Lib.Controllers.AIController.ShouldDisableAsync()
   at async Task LenovoLegionToolkit.Lib.Controllers.AIController.StopAsync()
   at async Task LenovoLegionToolkit.Lib.Controllers.AIController.StartIfNeededAsync()
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler) ---> System.Management.ManagementException: Invalid object 
   at void System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at ManagementBaseObject System.Management.ManagementObject.InvokeMethod(string methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
   at async Task<T> LenovoLegionToolkit.Lib.System.Management.WMI.CallAsync<T>(string scope, FormattableString query, string methodName, Dictionary<string, object> methodParams, Func<PropertyDataCollection, T> converter)
   --- End of inner exception stack trace ---

### Additional information

Previously I had toolkit installed, then when troubleshooting an issue uninstalled it to go back to vantage.
Support came and swapped the motherboard, now i'm trying to install toolkit again and this is happening

**Comment by BartoszCichecki** [comment]
You are either missing drivers or something else is wrong with your OS (like broken WMI).

**Comment by BartoszCichecki** [comment]
Hotfix is released now. This is a first time there is crash due to BIOS update, so apologies for scepticism.

**Comment by jeffkk** [comment]
Wow! Thank you so much for the quick response

**Comment by BartoszCichecki** [comment]
I hope the issue you have is the same one as the other people. If not, the problem is elsewhere, but just wanted to let you know.
