### ISSUE TITLE
bug when installing nvidia driver

### ISSUE THREAD

**Issue by yassinabdelhedi** [BartoszCichecki/LenovoLegionToolkit#1343]
### Rules

- [X] I made myself familiar with the README.
- [ ] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

latest version to this date

### OS

windows 10 

### Device

Legion 5 15ACH6H

### BIOS version

GKCN64WW

### What's wrong?

![error](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75133328/1449ef6d-7326-4d0f-b936-77ac7c124a21)
when i installed nvidia driver i got this error
and it made the gpu graphic in the app switch between integrated graphics and nvidia
![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/75133328/c0c9694f-c289-4dea-9a89-a009d8d23f32)

### How to reproduce the bug?

install nvidia driver
install lenovo legion toolkit 
disable hybrid mode
enable descrete gpu(to disable integrated graphics)
uninstall nvidia driver and reinstall them

### What is the behavior that you expected?

donno???fix it

### Logs

Application_DispatcherUnhandledException
=== Exception ===
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (87): Paramètre incorrect.
   at WindowsDisplayAPI.DisplayConfig.PathInfo.GetPathInfos(QueryDeviceConfigFlags flags, DisplayConfigTopologyId& topologyId)
   at WindowsDisplayAPI.DisplayConfig.PathInfo.GetAllPaths(Boolean virtualModeAware)
   at WindowsDisplayAPI.DisplayConfig.PathDisplayAdapter.GetAdapters()
   at WindowsDisplayAPI.DisplayAdapter.ToPathDisplayAdapter()
   at LenovoLegionToolkit.Lib.Extensions.DisplayExtensions.GetAdvancedColorInfo(Display display)
   at LenovoLegionToolkit.Lib.Listeners.DisplayConfigurationListener.GetHDRStatus()
   at LenovoLegionToolkit.Lib.Listeners.DisplayConfigurationListener.SystemEvents_DisplaySettingsChanged(Object sender, EventArgs e)
   at InvokeStub_EventHandler.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.Win32.SystemEvents.SystemEventInvokeInfo.InvokeCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at object System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
   at object Delegate.DynamicInvokeImpl(object[] args)
   at void Microsoft.Win32.SystemEvents+SystemEventInvokeInfo.InvokeCallback(object arg)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler) ---> System.ComponentModel.Win32Exception: Paramètre incorrect.
   at PathInfo[] WindowsDisplayAPI.DisplayConfig.PathInfo.GetPathInfos(QueryDeviceConfigFlags flags, out DisplayConfigTopologyId topologyId)
   at PathInfo[] WindowsDisplayAPI.DisplayConfig.PathInfo.GetAllPaths(bool virtualModeAware)
   at PathDisplayAdapter[] WindowsDisplayAPI.DisplayConfig.PathDisplayAdapter.GetAdapters()
   at PathDisplayAdapter WindowsDisplayAPI.DisplayAdapter.ToPathDisplayAdapter()
   at DisplayAdvancedColorInfo LenovoLegionToolkit.Lib.Extensions.DisplayExtensions.GetAdvancedColorInfo(Display display)
   at bool? LenovoLegionToolkit.Lib.Listeners.DisplayConfigurationListener.GetHDRStatus()
   at void LenovoLegionToolkit.Lib.Listeners.DisplayConfigurationListener.SystemEvents_DisplaySettingsChanged(object sender, EventArgs e)
   at object InvokeStub_EventHandler.Invoke(object, Span<object>)
   at object System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---

**Comment by BartoszCichecki** [comment]
Which version are you using?

**Comment by BartoszCichecki** [comment]
Not enough information provided. Closing.

**Comment by yassinabdelhedi** [comment]
hh how to know the version
