### ISSUE TITLE
Automation policy errors

### ISSUE THREAD

**Issue by XuChunHo** [BartoszCichecki/LenovoLegionToolkit#1427]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.24.1

### OS

windows 11 home 22H2

### Device

Legion Y7000P IRX9

### BIOS version

NMCN22WW

### What's wrong?

After my computer is updated to the latest version, the original power supply is recognized as a low-power supply when connected, resulting in an execution error of the automation strategy.

### How to reproduce the bug?

断开电源再接上

### What is the behavior that you expected?

识别错误

### Logs

[07/09/2024 11:48:27.374] [24] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:27.738] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 5, MaxUtilization: 100, CoreClock: 2934, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:28.814] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2318, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:29.886] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2077, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:30.953] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 2309, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:32.031] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2059, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 56, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:32.375] [24] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:32.376] [24] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:32.379] [24] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:32.381] [24] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:33.108] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 6, MaxUtilization: 100, CoreClock: 3561, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:33.836] [1] [DeviceInformationWindow.xaml.cs#56:RefreshAsync] Couldn't load warranty info.
=== Exception ===
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.HttpIOException: The response ended prematurely. (ResponseEnded)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at LenovoLegionToolkit.Lib.Utils.WarrantyChecker.GetStandardWarrantyInfo(HttpClient httpClient, MachineInformation machineInformation, CancellationToken token)
   at LenovoLegionToolkit.Lib.Utils.WarrantyChecker.GetWarrantyInfo(MachineInformation machineInformation, Boolean forceRefresh, CancellationToken token)
   at LenovoLegionToolkit.WPF.Windows.Utils.DeviceInformationWindow.RefreshAsync(Boolean forceRefresh)

=== Exception demystified ===
System.Net.Http.HttpRequestException: An error occurred while sending the request.
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
   at async ValueTask<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, bool async, bool doRequestAuth, CancellationToken cancellationToken)
   at async ValueTask<HttpResponseMessage> System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request)+Core(?)
   at async Task<WarrantyInfo?> LenovoLegionToolkit.Lib.Utils.WarrantyChecker.GetStandardWarrantyInfo(HttpClient httpClient, MachineInformation machineInformation, CancellationToken token)
   at async Task<WarrantyInfo?> LenovoLegionToolkit.Lib.Utils.WarrantyChecker.GetWarrantyInfo(MachineInformation machineInformation, bool forceRefresh, CancellationToken token)
   at async Task LenovoLegionToolkit.WPF.Windows.Utils.DeviceInformationWindow.RefreshAsync(bool forceRefresh) ---> System.Net.Http.HttpIOException: The response ended prematurely. (ResponseEnded)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

[07/09/2024 11:48:34.179] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 5, MaxUtilization: 100, CoreClock: 2736, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:35.260] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 2035, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:36.351] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2168, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:37.383] [24] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:37.385] [24] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:37.387] [24] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:37.388] [24] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:37.430] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2032, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:38.502] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1928, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:39.583] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 1, MaxUtilization: 100, CoreClock: 1901, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:40.663] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1923, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:41.742] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1881, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:42.390] [47] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:42.397] [47] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:42.401] [47] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:42.404] [47] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:42.821] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1941, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:43.894] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1969, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:44.967] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2136, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:46.037] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1844, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:47.115] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2037, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:47.406] [33] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:47.413] [33] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:47.417] [33] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:47.420] [33] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:48.192] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1963, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:49.273] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1922, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:50.350] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2090, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:51.427] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1974, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:52.422] [33] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:52.423] [33] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:52.431] [33] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:52.432] [33] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:52.493] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1926, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:53.564] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2065, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:54.641] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1960, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:55.723] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 1902, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:56.799] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 1957, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:57.433] [33] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:48:57.441] [33] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:48:57.447] [33] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:48:57.450] [33] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:48:57.867] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1878, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:48:58.936] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 1, MaxUtilization: 100, CoreClock: 1868, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:00.009] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 5, MaxUtilization: 100, CoreClock: 2132, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:01.084] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 2054, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:02.161] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 1, MaxUtilization: 100, CoreClock: 1815, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:02.451] [47] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:49:02.458] [47] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:49:02.462] [47] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:49:02.463] [47] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:49:03.243] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1806, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:04.320] [33] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 1876, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:05.391] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 2005, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:06.472] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 2, MaxUtilization: 100, CoreClock: 2051, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:07.464] [47] [GPUController.cs#184:RefreshLoopAsync] Will refresh...
[07/09/2024 11:49:07.465] [47] [GPUController.cs#222:RefreshStateAsync] Refresh in progress...
[07/09/2024 11:49:07.469] [47] [GPUController.cs#253:RefreshStateAsync] Powered off [state=PoweredOff, processes.Count=0, gpuInstanceId=]
[07/09/2024 11:49:07.470] [47] [GPUController.cs#189:RefreshLoopAsync] Refreshed
[07/09/2024 11:49:07.554] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 3, MaxUtilization: 100, CoreClock: 2102, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:08.618] [47] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 5, MaxUtilization: 100, CoreClock: 2969, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]
[07/09/2024 11:49:09.672] [24] [AbstractSensorsController.cs#95:GetDataAsync] Current data: CPU: Utilization: 5, MaxUtilization: 100, CoreClock: 3229, MaxCoreClock: 8500, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 57, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600, GPU: Utilization: -1, MaxUtilization: 100, CoreClock: -1, MaxCoreClock: -1, MemoryClock: -1, MaxMemoryClock: -1, Temperature: 35, MaxTemperature: 100, FanSpeed: 0, MaxFanSpeed: 5600 [type=SensorsControllerV3]

**Comment by BartoszCichecki** [comment]
I don't know which updates you did. That would be an obvious information to provide, right?

Whether a power supply is "low power" is an information provided by EC.

You might want to reset EC (instructions are on the Disord server linked in README) when you encounter errors like this.
