### ISSUE TITLE
Hardware monitoring information cannot be displayed

### ISSUE THREAD

**Issue by miku3901** [BartoszCichecki/LenovoLegionToolkit#1479]
### Version

2.24.1

### OS

Windows 11 Pro 23H2

### Device

Legion Y7000P 2020H

### BIOS version

EFCN59WW

### What is wrong?

![屏幕截图 2024-10-31 225304](https://github.com/user-attachments/assets/cf77fc3f-6d2c-4fb1-8456-f128d163cde9)
The hardware monitoring information, which should be displayed at the top of the interface, cannot be shown on my device.

### What did you try already?

 replace multiple different LLT versions including the latest one, upgrade the Windows version, and switch to various BIOS versions.

### How to reproduce the bug?

N/A

### What is the behavior that you expected?

LLT displays the hardware monitoring information of the device on the interface

### Logs

[26/08/2024 17:51:27.009] [1] [App.xaml.cs#315:CheckCompatibilityAsync] Compatibility check OVERRIDE. [Vendor=Acidanthera, Model=1.0, MachineType=MacBookPro16,1, version=2.23.1.0, build=20240807195202]
[26/08/2024 17:51:27.013] [1] [App.xaml.cs#101:Application_Startup] Starting... [version=2.23.1.0, build=20240807195202, os=Microsoft Windows NT 10.0.19045.0, dotnet=8.0.5]
[26/08/2024 17:51:27.129] [1] [Registry.cs#78:ObserveValue] Starting listener... [hive=S-1-5-21-60271235-3683991939-3213061665-1001, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-60271235-3683991939-3213061665-1001\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' AND ValueName = 'AppsUseLightTheme', key=AppsUseLightTheme]
[26/08/2024 17:51:27.185] [1] [Registry.cs#91:ObserveValue] Started listener [hive=S-1-5-21-60271235-3683991939-3213061665-1001, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-60271235-3683991939-3213061665-1001\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' AND ValueName = 'AppsUseLightTheme', key=AppsUseLightTheme]
[26/08/2024 17:51:27.185] [1] [Registry.cs#78:ObserveValue] Starting listener... [hive=S-1-5-21-60271235-3683991939-3213061665-1001, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-60271235-3683991939-3213061665-1001\\Software\\Microsoft\\Windows\\DWM' AND ValueName = 'ColorizationColor', key=ColorizationColor]
[26/08/2024 17:51:27.201] [1] [Registry.cs#91:ObserveValue] Started listener [hive=S-1-5-21-60271235-3683991939-3213061665-1001, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-60271235-3683991939-3213061665-1001\\Software\\Microsoft\\Windows\\DWM' AND ValueName = 'ColorizationColor', key=ColorizationColor]
[26/08/2024 17:51:27.202] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=WinKeyListener]
[26/08/2024 17:51:27.238] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=ThermalModeListener]
[26/08/2024 17:51:27.256] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=SpecialKeyListener]
[26/08/2024 17:51:27.271] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=RGBKeyboardBacklightListener]
[26/08/2024 17:51:27.287] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=PowerModeListener]
[26/08/2024 17:51:27.353] [10] [Power.cs#67:IsChargingNormally] Mode = 1
[26/08/2024 17:51:27.387] [1] [NativeWindowsMessageListener.cs#187:WndProc] Event received: Monitor On
[26/08/2024 17:51:27.388] [1] [NativeWindowsMessageListener.cs#209:WndProc] Event received: Lid Opened
[26/08/2024 17:51:27.388] [1] [NativeWindowsMessageListener.cs#225:WndProc] Event received: Battery Saver enabled
[26/08/2024 17:51:27.389] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=LightingChangeListener]
[26/08/2024 17:51:27.390] [10] [AbstractWmiFeature.cs#29:GetStateAsync] Getting state... [feature=PowerModeFeature]
[26/08/2024 17:51:27.412] [1] [AbstractWMIListener.cs#34:StartAsync] Couldn't start listener. [listener=LightingChangeListener]
=== Exception ===
System.Management.ManagementException: 无效类 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementEventWatcher.Start()
   at LenovoLegionToolkit.Lib.System.Management.WMI.Listen(String scope, FormattableString query, Action`1 handler)
   at LenovoLegionToolkit.Lib.System.Management.WMI.LenovoLightingEvent.Listen(Action`1 handler)
   at LenovoLegionToolkit.Lib.Listeners.AbstractWMIListener`3.StartAsync()

=== Exception demystified ===
System.Management.ManagementException: 无效类 
   at void System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at void System.Management.ManagementEventWatcher.Start()
   at LambdaDisposable LenovoLegionToolkit.Lib.System.Management.WMI.Listen(string scope, FormattableString query, Action<PropertyDataCollection> handler)
   at IDisposable LenovoLegionToolkit.Lib.System.Management.WMI+LenovoLightingEvent.Listen(Action<int> handler)
   at Task LenovoLegionToolkit.Lib.Listeners.AbstractWMIListener<TEventArgs, TValue, TRawValue>.StartAsync()

[26/08/2024 17:51:27.452] [7] [AbstractWmiFeature.cs#35:GetStateAsync] State is Balance [feature=PowerModeFeature]
[26/08/2024 17:51:27.480] [1] [AbstractWMIListener.cs#27:StartAsync] Starting... [listener=DisplayBrightnessListener]
[26/08/2024 17:51:27.512] [9] [AbstractSoftwareDisabler.cs#34:GetStatusAsync] Running services count: 1. [type=VantageDisabler, services=ImControllerService]
[26/08/2024 17:51:27.512] [9] [AbstractSoftwareDisabler.cs#35:GetStatusAsync] Running processes count: 1. [type=VantageDisabler, processes=Lenovo.Modern.ImController]
[26/08/2024 17:51:27.514] [9] [AbstractSoftwareDisabler.cs#51:GetStatusAsync] Status: True,True [type=VantageDisabler]
[26/08/2024 17:51:27.515] [1] [App.xaml.cs#378:LogSoftwareStatusAsync] Vantage status: Enabled
[26/08/2024 17:51:27.520] [9] [AbstractSoftwareDisabler.cs#34:GetStatusAsync] Running services count: 0. [type=LegionZoneDisabler, services=]
[26/08/2024 17:51:27.520] [9] [AbstractSoftwareDisabler.cs#35:GetStatusAsync] Running processes count: 0. [type=LegionZoneDisabler, processes=]
[26/08/2024 17:51:27.522] [9] [AbstractSoftwareDisabler.cs#51:GetStatusAsync] Status: False,False [type=LegionZoneDisabler]
[26/08/2024 17:51:27.522] [1] [App.xaml.cs#381:LogSoftwareStatusAsync] LegionZone status: NotFound
[26/08/2024 17:51:27.528] [9] [AbstractSoftwareDisabler.cs#34:GetStatusAsync] Running services count: 1. [type=FnKeysDisabler, services=LenovoFnAndFunctionKeys]
[26/08/2024 17:51:27.529] [9] [AbstractSoftwareDisabler.cs#35:GetStatusAsync] Running processes count: 1. [type=FnKeysDisabler, processes=LenovoUtilityService]
[26/08/2024 17:51:27.530] [9] [AbstractSoftwareDisabler.cs#51:GetStatusAsync] Status: True,True [type=FnKeysDisabler]
[26/08/2024 17:51:27.531] [1] [App.xaml.cs#384:LogSoftwareStatusAsync] FnKeys status: Enabled
[26/08/2024 17:51:27.548] [7] [WindowsPowerModeController.cs#32:SetPowerModeAsync] Ignoring... [powerModeMappingMode=WindowsPowerPlan]
[26/08/2024 17:51:27.550] [7] [WindowsPowerPlanController.cs#40:SetPowerPlanAsync] Activating... [powerModeState=Balance, alwaysActivateDefaults=True]
[26/08/2024 17:51:27.551] [7] [WindowsPowerPlanController.cs#55:SetPowerPlanAsync] Power plan to be activated is 381b4222-f694-41f0-9685-ff5bb260df2e [isDefault=False]
[26/08/2024 17:51:27.566] [35] [AbstractSoftwareDisabler.cs#34:GetStatusAsync] Running services count: 1. [type=VantageDisabler, services=ImControllerService]
[26/08/2024 17:51:27.567] [35] [AbstractSoftwareDisabler.cs#35:GetStatusAsync] Running processes count: 1. [type=VantageDisabler, processes=Lenovo.Modern.ImController]
[26/08/2024 17:51:27.567] [1] [App.xaml.cs#430:InitPowerModeFeatureAsync] Ensuring god mode state is applied...
[26/08/2024 17:51:27.568] [1] [AbstractWmiFeature.cs#29:GetStateAsync] Getting state... [feature=PowerModeFeature]
[26/08/2024 17:51:27.568] [35] [AbstractSoftwareDisabler.cs#51:GetStatusAsync] Status: True,True [type=VantageDisabler]
[26/08/2024 17:51:27.569] [35] [WindowsPowerPlanController.cs#121:ShouldSetPowerPlanAsync] Criteria for activation not met [isDefault=False, alwaysActivateDefaults=True, status=Enabled]
[26/08/2024 17:51:27.569] [35] [WindowsPowerPlanController.cs#60:SetPowerPlanAsync] Power plan 381b4222-f694-41f0-9685-ff5bb260df2e will not be activated [isDefault=False]
[26/08/2024 17:51:27.596] [9] [AbstractWmiFeature.cs#35:GetStateAsync] State is Balance [feature=PowerModeFeature]
[26/08/2024 17:51:27.624] [1] [App.xaml.cs#447:InitPowerModeFeatureAsync] Ensuring correct power plan is set...
[26/08/2024 17:51:27.625] [1] [AbstractWmiFeature.cs#29:GetStateAsync] Getting state... [feature=PowerModeFeature]
[26/08/2024 17:51:27.653] [9] [AbstractWmiFeature.cs#35:GetStateAsync] State is Balance [feature=PowerModeFeature]
[26/08/2024 17:51:27.653] [9] [WindowsPowerModeController.cs#32:SetPowerModeAsync] Ignoring... [powerModeMappingMode=WindowsPowerPlan]
[26/08/2024 17:51:27.654] [9] [WindowsPowerPlanController.cs#40:SetPowerPlanAsync] Activating... [powerModeState=Balance, alwaysActivateDefaults=True]
[26/08/2024 17:51:27.654] [9] [WindowsPowerPlanController.cs#55:SetPowerPlanAsync] Power plan to be activated is 381b4222-f694-41f0-9685-ff5bb260df2e [isDefault=False]
[26/08/2024 17:51:27.657] [9] [AbstractSoftwareDisabler.cs#34:GetStatusAsync] Running services count: 1. [type=VantageDisabler, services=ImControllerService]
[26/08/2024 17:51:27.658] [9] [AbstractSoftwareDisabler.cs#35:GetStatusAsync] Running processes count: 1. [type=VantageDisabler, processes=Lenovo.Modern.ImController]
[26/08/2024 17:51:27.659] [9] [AbstractSoftwareDisabler.cs#51:GetStatusAsync] Status: True,True [type=VantageDisabler]
[26/08/2024 17:51:27.660] [9] [WindowsPowerPlanController.cs#121:ShouldSetPowerPlanAsync] Criteria for activation not met [isDefault=False, alwaysActivateDefaults=True, status=Enabled]
[26/08/2024 17:51:27.660] [9] [WindowsPowerPlanController.cs#60:SetPowerPlanAsync] Power plan 381b4222-f694-41f0-9685-ff5bb260df2e will not be activated [isDefault=False]
[26/08/2024 17:51:27.663] [1] [AbstractDriverFeature.cs#35:GetStateAsync] Getting state... [feature=BatteryFeature]
[26/08/2024 17:51:27.664] [9] [AbstractDriverFeature.cs#40:GetStateAsync] Buffer value: 268828704 [feature=BatteryFeature]
[26/08/2024 17:51:27.665] [9] [AbstractDriverFeature.cs#46:GetStateAsync] State is Conservation [feature=BatteryFeature]
[26/08/2024 17:51:27.667] [1] [App.xaml.cs#467:InitBatteryFeatureAsync] Ensuring correct battery mode is set...
[26/08/2024 17:51:27.668] [1] [AbstractDriverFeature.cs#35:GetStateAsync] Getting state... [feature=BatteryFeature]
[26/08/2024 17:51:27.668] [9] [AbstractDriverFeature.cs#40:GetStateAsync] Buffer value: 268828704 [feature=BatteryFeature]
[26/08/2024 17:51:27.669] [9] [AbstractDriverFeature.cs#46:GetStateAsync] State is Conservation [feature=BatteryFeature]
[26/08/2024 17:51:27.677] [1] [App.xaml.cs#494:InitRgbKeyboardControllerAsync] RGB keyboard is not supported.
[26/08/2024 17:51:27.680] [1] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=1]
[26/08/2024 17:51:27.745] [9] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=2]
[26/08/2024 17:51:27.808] [9] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=3]
[26/08/2024 17:51:27.872] [9] [SpectrumKeyboardBacklightController.cs#599:GetDeviceHandleAsync] Handle couldn't be refreshed.
[26/08/2024 17:51:27.873] [1] [App.xaml.cs#529:InitSpectrumKeyboardControllerAsync] Spectrum keyboard is not supported.
[26/08/2024 17:51:27.896] [1] [GPUOverclockController.cs#71:IsSupportedAsync] NVAPI status: True.
[26/08/2024 17:51:27.922] [35] [GPUOverclockController.cs#96:IsSupportedAsync] Supports GPU OC status: True
[26/08/2024 17:51:27.923] [1] [App.xaml.cs#547:InitGpuOverclockControllerAsync] Ensuring GPU overclock is applied...
[26/08/2024 17:51:27.926] [1] [App.xaml.cs#558:InitGpuOverclockControllerAsync] GPU overclock not needed.
[26/08/2024 17:51:27.927] [1] [App.xaml.cs#392:InitHybridModeAsync] Initializing hybrid mode...
[26/08/2024 17:51:27.948] [1] [App.xaml.cs#409:InitAutomationProcessorAsync] Initializing automation processor...
[26/08/2024 17:51:27.954] [1] [AutomationProcessor.cs#320:UpdateListenersAsync] Stopping listeners...
[26/08/2024 17:51:27.956] [1] [AbstractAutoListener.cs#35:StartStopAsync] Subscribers: 0. [type=GameAutoListener]
[26/08/2024 17:51:27.957] [1] [AbstractAutoListener.cs#70:StopInternalAsync] Already stopped. [type=GameAutoListener]
[26/08/2024 17:51:27.957] [1] [AbstractAutoListener.cs#35:StartStopAsync] Subscribers: 0. [type=ProcessAutoListener]
[26/08/2024 17:51:27.958] [1] [AbstractAutoListener.cs#70:StopInternalAsync] Already stopped. [type=ProcessAutoListener]
[26/08/2024 17:51:27.958] [1] [AbstractAutoListener.cs#35:StartStopAsync] Subscribers: 0. [type=TimeAutoListener]
[26/08/2024 17:51:27.959] [1] [AbstractAutoListener.cs#70:StopInternalAsync] Already stopped. [type=TimeAutoListener]
[26/08/2024 17:51:27.959] [1] [AbstractAutoListener.cs#35:StartStopAsync] Subscribers: 0. [type=UserInactivityAutoListener]
[26/08/2024 17:51:27.959] [1] [AbstractAutoListener.cs#70:StopInternalAsync] Already stopped. [type=UserInactivityAutoListener]
[26/08/2024 17:51:27.960] [1] [AbstractAutoListener.cs#35:StartStopAsync] Subscribers: 0. [type=WiFiAutoListener]
[26/08/2024 17:51:27.960] [1] [AbstractAutoListener.cs#70:StopInternalAsync] Already stopped. [type=WiFiAutoListener]
[26/08/2024 17:51:27.960] [1] [AutomationProcessor.cs#329:UpdateListenersAsync] Stopped listeners...
[26/08/2024 17:51:27.961] [1] [AutomationProcessor.cs#334:UpdateListenersAsync] Not enabled. Will not start listeners.
[26/08/2024 17:51:27.961] [1] [AutomationProcessor.cs#110:RunOnStartup] Not enabled. Pipeline run on startup ignored.
[26/08/2024 17:51:27.964] [1] [AIController.cs#43:StartIfNeededAsync] Not supported.
[26/08/2024 17:51:27.965] [1] [HWiNFOIntegration.cs#48:StopAsync] Stopping...
[26/08/2024 17:51:27.966] [1] [HWiNFOIntegration.cs#59:StopAsync] Stopped.
[26/08/2024 17:51:27.967] [1] [IpcServer.cs#54:StopAsync] Stopping...
[26/08/2024 17:51:27.968] [1] [IpcServer.cs#60:StopAsync] Stopped
[26/08/2024 17:51:27.972] [1] [Autorun.cs#30:Validate] Validating autorun...
[26/08/2024 17:51:27.986] [1] [Autorun.cs#59:Validate] Autorun settings seems to be fine.
[26/08/2024 17:51:28.018] [1] [App.xaml.cs#157:Application_Startup] Sending MainWindow to tray...
[26/08/2024 17:51:28.085] [35] [UpdateChecker.cs#44:CheckAsync] Checking...
[26/08/2024 17:51:28.129] [1] [App.xaml.cs#172:Application_Startup] Start up complete
[26/08/2024 17:51:28.133] [1] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=1]
[26/08/2024 17:51:28.192] [7] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=2]
[26/08/2024 17:51:28.232] [1] [DashboardPage.xaml.cs#50:RefreshAsync] Groups:
[26/08/2024 17:51:28.233] [1] [DashboardPage.xaml.cs#52:RefreshAsync]  - Type: Power, CustomName: , Items: PowerMode,BatteryMode,BatteryNightChargeMode,AlwaysOnUsb,InstantBoot,FlipToStart
[26/08/2024 17:51:28.236] [1] [DashboardPage.xaml.cs#52:RefreshAsync]  - Type: Graphics, CustomName: , Items: HybridMode,DiscreteGpu,OverclockDiscreteGpu
[26/08/2024 17:51:28.236] [1] [DashboardPage.xaml.cs#52:RefreshAsync]  - Type: Display, CustomName: , Items: Resolution,RefreshRate,DpiScale,Hdr,OverDrive,TurnOffMonitors
[26/08/2024 17:51:28.237] [1] [DashboardPage.xaml.cs#52:RefreshAsync]  - Type: Other, CustomName: , Items: Microphone,WhiteKeyboardBacklight,PanelLogoBacklight,PortsBacklight,TouchpadLock,FnLock,WinKeyLock
[26/08/2024 17:51:28.278] [9] [SpectrumKeyboardBacklightController.cs#584:GetDeviceHandleAsync] Refreshing handle... [retry=3]
[26/08/2024 17:51:28.341] [9] [SpectrumKeyboardBacklightController.cs#599:GetDeviceHandleAsync] Handle couldn't be refreshed.
[26/08/2024 17:51:34.000] [35] [UpdateChecker.cs#65:CheckAsync] Checked [updates.Length=1]
[26/08/2024 17:51:34.005] [1] [NotificationsManager.cs#39:OnNotificationReceived] Notification Type: UpdateAvailable, Args: [2.24.0] received
[26/08/2024 17:51:34.037] [1] [NotificationsManager.cs#223:OnNotificationReceived] Notification Type: UpdateAvailable, Args: [2.24.0] shown.
[26/08/2024 17:51:34.038] [1] [NotificationsManager.cs#39:OnNotificationReceived] Notification Type: UpdateAvailable, Args: [2.24.0] received
[26/08/2024 17:51:34.060] [1] [NotificationsManager.cs#223:OnNotificationReceived] Notification Type: UpdateAvailable, Args: [2.24.0] shown.
[26/08/2024 17:51:36.416] [1] [NativeWindowsMessageListener.cs#124:WndProc] Event received: Device Arrival [name=\\?\SWD#PRINTENUM#{8D59DF21-507D-4A93-AE9B-C9EABBA84A84}#{0ecef634-6ef0-472a-8085-5ad023ecbccd}]
[26/08/2024 17:52:23.887] [1] [NativeWindowsMessageListener.cs#124:WndProc] Event received: Device Arrival [name=\\?\{5d624f94-8850-40c3-a3fa-a4fd2080baf3}#vwifimp_wfd#4&63d2e00&0&12#{ad498944-762f-11d0-8dcb-00c04fc3358c}\{49B18669-7B75-47FB-8133-6D2F5B406A17}]
[26/08/2024 17:52:23.905] [1] [NativeWindowsMessageListener.cs#124:WndProc] Event received: Device Arrival [name=\\?\{5d624f94-8850-40c3-a3fa-a4fd2080baf3}#vwifimp_wfd#4&63d2e00&0&12#{cac88484-7515-4c03-82e6-71a87abac361}]
[26/08/2024 17:53:39.391] [1] [MainWindow.xaml.cs#116:MainWindow_Closing] Minimizing...

**Comment by BartoszCichecki** [comment]
If it's not there, it's not supported on your laptop.
