### ISSUE TITLE
[COMPATIBILITY]: Apply for IdeaPad 5 Pro 16ARH7 - Type 82SN (China Edition of Lenovo Xiaoxin Pro 16 ARH7)

### ISSUE THREAD

**Issue by Steven9178Anotheraccount** [BartoszCichecki/LenovoLegionToolkit#257]
### Version

2.62

### OS

Windows 11 22H2 22621.608

### Device

Lenovo IdeaPad 5 Pro ARH7/Lenovo Xiaoxin Pro 16 ARH7

### Which features of the application did you test?

Keyboard brightness
Actions
Theme
Accent color
Disable Vantage/Hotkeys

### Which features of the application do not work as expected?

Nope

**Comment by Steven9178Anotheraccount** [comment]
And another one cannot be used
Fn+R
Cannot switch screen refresh rate

**Comment by BartoszCichecki** [comment]
Some keyboard do not send any codes for Fn+R, but just to make sure, start LLT, press Fn+R a couple of times and upload a log here. I'll check if the keycode is not sent or if it's different. If there is a new keycode used I'll add support for it.

Just to clarify "Xiaoxin" is the name of the lineup like IdeaPad right?

**Comment by Steven9178Anotheraccount** [comment]
maybe it is
![图片](https://user-images.githubusercontent.com/115457858/194835833-4eb9e71d-5ef6-478d-8fed-a5fc7ffe6b37.png)
![图片](https://user-images.githubusercontent.com/115457858/194836154-ae439fd1-d525-4ef2-9afa-214626cfcd7e.png)

**Comment by Steven9178Anotheraccount** [comment]
Version

2.62
OS

Windows 11 22H2 22621.608
Device

Lenovo IdeaPad 5 Pro ARH7/Lenovo Xiaoxin Pro 16 ARH7
BIOS version

J4CN33WW
What's wrong?

图片
How to reproduce the bug?

    Go to Dashboard
    Find "Betty Mode"
    Click "Rapid Charge"
    See error

What is the behavior that you expected?

Fix it
Logs

error log
=== Exception ===
System.InvalidOperationException: Unknown battery state: 34304
at LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(UInt32 state)
at LenovoLegionToolkit.Lib.Features.AbstractDriverFeature1.GetStateAsync() at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl1.OnStateChange(ComboBox comboBox, IFeature1 feature, Nullable1 newValue, Nullable1 oldValue) at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl1.ComboBox_SelectionChanged(Object sender, SelectionChangedEventArgs e)
at System.Threading.Tasks.Task.<>c.b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Unknown battery state: 34304
at Task LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(uint state)
at async Task LenovoLegionToolkit.Lib.Features.AbstractDriverFeature.GetStateAsync()
at async Task LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl.OnStateChange(ComboBox comboBox, IFeature feature, T? newValue, T? oldValue)
at async void LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl.ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

normal log
=== Exception ===
System.InvalidOperationException: Unknown battery state: 34304
at LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(UInt32 state)
at LenovoLegionToolkit.Lib.Features.AbstractDriverFeature1.GetStateAsync() at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl1.OnStateChange(ComboBox comboBox, IFeature1 feature, Nullable1 newValue, Nullable1 oldValue) at LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl1.ComboBox_SelectionChanged(Object sender, SelectionChangedEventArgs e)
at System.Threading.Tasks.Task.<>c.b__128_0(Object state)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: Unknown battery state: 34304
at Task LenovoLegionToolkit.Lib.Features.BatteryFeature.FromInternalAsync(uint state)
at async Task LenovoLegionToolkit.Lib.Features.AbstractDriverFeature.GetStateAsync()
at async Task LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl.OnStateChange(ComboBox comboBox, IFeature feature, T? newValue, T? oldValue)
at async void LenovoLegionToolkit.WPF.Controls.AbstractComboBoxFeatureCardControl.ComboBox_SelectionChanged(object sender, SelectionChangedEventArgs e)
at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
Do you have Lenovo software installed?

Lenovo Vantage is installed
Lenovo Hotkeys is installed
None of the above

Did you disable any Lenovo software using Lenovo Legion Toolkit?

Lenovo Vantage
Lenovo Hotkeys
I disabled some things on my own (please write below what you did)

Additional information

No response

**Comment by Steven9178Anotheraccount** [comment]
Sorry, I can't switch it.

**Comment by qwertyue** [comment]
> Some keyboard do not send any codes for Fn+R, but just to make sure, start LLT, press Fn+R a couple of times and upload a log here. I'll check if the keycode is not sent or if it's different. If there is a new keycode used I'll add support for it.
> 
> Just to clarify "Xiaoxin" is the name of the lineup like IdeaPad right?

After investigation, the configurations of Lenovo IdeaPad 5 Pro ARH7 and Lenovo Xiaoxin Pro 16 ARH7 are basically the same, maybe they are only sold to different regions.

**Comment by BartoszCichecki** [comment]
Can you provide a log? I asked twice already. I suspect that IdeaPad Pro laptops are too different from IdeaPad Gaming and Legion.

**Comment by Steven9178Anotheraccount** [comment]
> After investigation, the configurations of Lenovo IdeaPad 5 Pro ARH7 and Lenovo Xiaoxin Pro 16 ARH7 are basically the same, maybe they are only sold to different regions.

Hey,  you need creat new one.

**Comment by Steven9178Anotheraccount** [comment]
And this drive have Geforce RTX 3050/3050Ti.

**Comment by BartoszCichecki** [comment]
It looks like IdeaPad Pro devices are vastly different from Legion and IdeaPad gaming. Support will not be added.

**Comment by Steven9178Anotheraccount** [comment]
okay
