### ISSUE TITLE
[BUG]:  The software crashed when opened

### ISSUE THREAD

**Issue by john9999911** [BartoszCichecki/LenovoLegionToolkit#335]
### Version

2.6.5

### OS

windows 11 22h2 22623

### Device

y7000p 82ax

### BIOS version

i don't know

### What's wrong?

![image](https://user-images.githubusercontent.com/80616586/199065346-3b6ccced-66fa-4828-a020-2358617be94b.png)

### How to reproduce the bug?

Update the version to 2.6.5 and then it crashed.

### What is the behavior that you expected?

Normally use

### Logs

=== Exception ===
System.InvalidOperationException: DeviceIoControl returned 0, last error: 2
   at LenovoLegionToolkit.Lib.Features.AbstractDriverFeature`1.<>c__DisplayClass11_0.<SendCodeAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LenovoLegionToolkit.Lib.Features.WhiteKeyboardBacklightFeature.IsSupportedAsync()
   at LenovoLegionToolkit.WPF.Pages.KeyboardBacklightPage.IsSupportedAsync()
   at LenovoLegionToolkit.WPF.Windows.MainWindow.MainWindow_Loaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: DeviceIoControl returned 0, last error: 2
   at uint LenovoLegionToolkit.Lib.Features.AbstractDriverFeature<T>+<>c__DisplayClass11_0.<SendCodeAsync>b__0(?)+() => { }
   at async Task<bool> LenovoLegionToolkit.Lib.Features.WhiteKeyboardBacklightFeature.IsSupportedAsync()
   at async Task<bool> LenovoLegionToolkit.WPF.Pages.KeyboardBacklightPage.IsSupportedAsync()
   at async void LenovoLegionToolkit.WPF.Windows.MainWindow.MainWindow_Loaded(object sender, RoutedEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by john9999911** [comment]
By the way, i can use v2.6.4 normally.

**Comment by john9999911** [comment]
BIOS: EFCN50WW

**Comment by BartoszCichecki** [comment]
Thanks for reporting, next beta of 2.6.5 will have the issue fixed.
