### ISSUE TITLE
[BUG]: No keyboard settings

### ISSUE THREAD

**Issue by sebolio** [BartoszCichecki/LenovoLegionToolkit#433]
### Version

2.7.0

### OS

Win 11 22H2 nov

### Device

Legion 7 Slim

### BIOS version

HACN39WW

### What's wrong?

I can't see the Keyboard button in the sidebar. My keyboard is per-key rgb (i can set "rain" mode in iCue), however in iCue i can't see the actual keyboard, maybe it's related?

<img width="103" alt="image" src="https://user-images.githubusercontent.com/197329/204952086-f628136c-fc70-49f9-a51a-ad75e9fe23cb.png">

iCue:
<img width="942" alt="image" src="https://user-images.githubusercontent.com/197329/204952163-1ccb5753-408a-4f19-8d12-57f732f0ce81.png">

### How to reproduce the bug?

Open the program

### What is the behavior that you expected?

should have the keyboard button

### Logs

<details>
<summary>View logs</summary>

```
[01/12/2022 02:35:51.914] [18] [Compatibility.cs#88:GetMachineInformationAsync] Retrieved machine information:
[01/12/2022 02:35:51.915] [18] [Compatibility.cs#89:GetMachineInformationAsync]  * Vendor: 'LENOVO'
[01/12/2022 02:35:51.915] [18] [Compatibility.cs#90:GetMachineInformationAsync]  * Machine Type: '82K8'
[01/12/2022 02:35:51.916] [18] [Compatibility.cs#91:GetMachineInformationAsync]  * Model: 'Legion S7 15ACH6'
[01/12/2022 02:35:51.916] [18] [Compatibility.cs#92:GetMachineInformationAsync]  * BIOS: 'HACN39WW'
[01/12/2022 02:35:51.916] [18] [Compatibility.cs#93:GetMachineInformationAsync]  * SupportsACDetection: 'False'
[01/12/2022 02:35:51.922] [18] [Compatibility.cs#94:GetMachineInformationAsync]  * SupportsGodMode: 'True'
[01/12/2022 02:35:51.923] [18] [Compatibility.cs#95:GetMachineInformationAsync]  * SupportsExtendedHybridMode: 'False'
[01/12/2022 02:35:51.923] [18] [Compatibility.cs#96:GetMachineInformationAsync]  * SupportsIntelligentSubMode: 'True'
[01/12/2022 02:35:51.929] [1] [App.xaml.cs#197:CheckCompatibilityAsync] Compatibility check passed. [Vendor=LENOVO, Model=Legion S7 15ACH6, MachineType=82K8, BIOS=HACN39WW]
[01/12/2022 02:35:51.931] [1] [App.xaml.cs#60:Application_Startup] Starting... [version=2.7.0.0, build=20221126173116]
[01/12/2022 02:35:52.245] [1] [Registry.cs#25:Listen] Starting listener... [hive=S-1-5-21-4027595981-2640381605-302647938-1000, pathFormatted =SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-4027595981-2640381605-302647938-1000\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' AND ValueName = 'AppsUseLightTheme', key=AppsUseLightTheme]
[01/12/2022 02:35:52.258] [1] [Registry.cs#38:Listen] Started listener [hive=S-1-5-21-4027595981-2640381605-302647938-1000, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-4027595981-2640381605-302647938-1000\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize' AND ValueName = 'AppsUseLightTheme', key=AppsUseLightTheme]
[01/12/2022 02:35:52.258] [1] [Registry.cs#25:Listen] Starting listener... [hive=S-1-5-21-4027595981-2640381605-302647938-1000, pathFormatted =SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-4027595981-2640381605-302647938-1000\\Software\\Microsoft\\Windows\\DWM' AND ValueName = 'ColorizationColor', key=ColorizationColor]
[01/12/2022 02:35:52.265] [1] [Registry.cs#38:Listen] Started listener [hive=S-1-5-21-4027595981-2640381605-302647938-1000, pathFormatted=SELECT * FROM RegistryValueChangeEvent WHERE Hive = 'HKEY_USERS' AND KeyPath = 'S-1-5-21-4027595981-2640381605-302647938-1000\\Software\\Microsoft\\Windows\\DWM' AND ValueName = 'ColorizationColor', key=ColorizationColor]
[01/12/2022 02:35:52.268] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=WinKeyListener]
[01/12/2022 02:35:52.278] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=LightingChangeListener]
[01/12/2022 02:35:52.286] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=SpecialKeyListener]
[01/12/2022 02:35:52.330] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=RGBKeyboardBacklightListener]
[01/12/2022 02:35:52.360] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=PowerModeListener]
[01/12/2022 02:35:52.382] [1] [AbstractWMIListener.cs#42:StartAsync] Starting... [listener=ThermalModeListener]
[01/12/2022 02:35:52.406] [1] [App.xaml.cs#274:InitAutomationProcessor] Initializing automation processor...
[01/12/2022 02:35:52.434] [1] [AutomationProcessor.cs#348:UpdateListenersAsync] Stopping listeners...
[01/12/2022 02:35:52.435] [1] [AbstractWMIListener.cs#60:StopAsync] Stopping... [listener=InstanceEventListener]
[01/12/2022 02:35:52.435] [1] [AbstractWMIListener.cs#60:StopAsync] Stopping... [listener=InstanceEventListener]
[01/12/2022 02:35:52.436] [1] [AutomationProcessor.cs#354:UpdateListenersAsync] Stopped listeners...
[01/12/2022 02:35:52.436] [1] [AutomationProcessor.cs#359:UpdateListenersAsync] Not enabled. Will not start listeners.
[01/12/2022 02:35:52.437] [1] [AutomationProcessor.cs#116:RunOnStartup] Not enabled. Pipeline run on startup ignored.
[01/12/2022 02:35:52.454] [1] [App.xaml.cs#295:InitPowerModeFeature] Ensuring AI Mode is set...
[01/12/2022 02:35:52.456] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=PowerModeFeature]
[01/12/2022 02:35:52.467] [18] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Quiet [feature=PowerModeFeature]
[01/12/2022 02:35:52.470] [18] [AIModeController.cs#59:StartAsync] Starting...
[01/12/2022 02:35:52.481] [1] [App.xaml.cs#312:InitPowerModeFeature] Ensuring correct power plan is set...
[01/12/2022 02:35:52.482] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=PowerModeFeature]
[01/12/2022 02:35:52.493] [18] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Quiet [feature=PowerModeFeature]
[01/12/2022 02:35:52.498] [18] [Power.cs#66:ActivatePowerPlanAsync] Activating... [powerModeState=Quiet, alwaysActivateDefaults=True]
[01/12/2022 02:35:52.500] [18] [Power.cs#74:ActivatePowerPlanAsync] Power plan for power mode Quiet was not found in settings
[01/12/2022 02:35:52.503] [18] [Power.cs#81:ActivatePowerPlanAsync] Power plan to be activated is 16edbccd-dee9-4ec4-ace5-2f0b5f2a8975 [isDefault=True]
[01/12/2022 02:35:52.504] [18] [Power.cs#176:ShouldActivateAsync] Power plan is default and always active defaults is set
[01/12/2022 02:35:52.554] [18] [Power.cs#95:ActivatePowerPlanAsync] Available power plans:
[01/12/2022 02:35:52.554] [18] [Power.cs#97:ActivatePowerPlanAsync]  - Equilibrado [guid=381b4222-f694-41f0-9685-ff5bb260df2e, isActive=True]
[01/12/2022 02:35:52.556] [18] [Power.cs#104:ActivatePowerPlanAsync] Power plan 16edbccd-dee9-4ec4-ace5-2f0b5f2a8975 was not found
[01/12/2022 02:35:52.566] [1] [App.xaml.cs#339:InitRGBKeyboardController] RGB keyboard is not supported.
[01/12/2022 02:35:52.572] [1] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=1]
[01/12/2022 02:35:52.633] [8] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=2]
[01/12/2022 02:35:52.695] [8] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=3]
[01/12/2022 02:35:52.756] [8] [SpectrumKeyboardBacklightController.cs#535:GetDeviceHandleAsync] Handle couldn't be refreshed.
[01/12/2022 02:35:52.758] [1] [App.xaml.cs#374:InitSpectrumKeyboardController] Spectrum keyboard is not supported.
[01/12/2022 02:35:52.762] [1] [Autorun.cs#30:Validate] Validating autorun...
[01/12/2022 02:35:52.771] [1] [Autorun.cs#36:Validate] Autorun is not enabled.
[01/12/2022 02:35:52.940] [1] [App.xaml.cs#106:Application_Startup] Showing MainWindow...
[01/12/2022 02:35:52.982] [8] [UpdateChecker.cs#35:Check] Checking...
[01/12/2022 02:35:53.155] [1] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=1]
[01/12/2022 02:35:53.222] [32] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=2]
[01/12/2022 02:35:53.301] [32] [SpectrumKeyboardBacklightController.cs#520:GetDeviceHandleAsync] Refreshing handle... [retry=3]
[01/12/2022 02:35:53.323] [1] [App.xaml.cs#112:Application_Startup] Start up complete
[01/12/2022 02:35:53.367] [32] [SpectrumKeyboardBacklightController.cs#535:GetDeviceHandleAsync] Handle couldn't be refreshed.
[01/12/2022 02:35:53.423] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=PowerModeControl]
[01/12/2022 02:35:53.432] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=BatteryModeControl]
[01/12/2022 02:35:53.436] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=BatteryFeature]
[01/12/2022 02:35:53.439] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=AlwaysOnUSBControl]
[01/12/2022 02:35:53.439] [9] [AbstractDriverFeature.cs#48:GetStateAsync] State is Normal [feature=BatteryFeature]
[01/12/2022 02:35:53.442] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=AlwaysOnUSBFeature]
[01/12/2022 02:35:53.444] [9] [AbstractDriverFeature.cs#48:GetStateAsync] State is OnAlways [feature=AlwaysOnUSBFeature]
[01/12/2022 02:35:53.445] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=ToggleHybridModeControl]
[01/12/2022 02:35:53.452] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=RefreshRateControl]
[01/12/2022 02:35:53.456] [1] [RefreshRateFeature.cs#17:GetAllStatesAsync] Getting all refresh rates...
[01/12/2022 02:35:53.460] [1] [DisplayExtensions.cs#20:GetBuiltInDisplayAsync] Found displays:
[01/12/2022 02:35:53.465] [1] [DisplayExtensions.cs#22:GetBuiltInDisplayAsync]  - Display: \\.\DISPLAY1\Monitor0 (Generic PnP Monitor)
[01/12/2022 02:35:53.479] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=HDRControl]
[01/12/2022 02:35:53.481] [15] [RefreshRateFeature.cs#29:GetAllStatesAsync] Built in display found: Display: \\.\DISPLAY1\Monitor0 (Generic PnP Monitor)
[01/12/2022 02:35:53.482] [1] [HDRFeature.cs#13:IsSupportedAsync] Checking HDR support...
[01/12/2022 02:35:53.483] [1] [DisplayExtensions.cs#20:GetBuiltInDisplayAsync] Found displays:
[01/12/2022 02:35:53.483] [1] [DisplayExtensions.cs#22:GetBuiltInDisplayAsync]  - Display: \\.\DISPLAY1\Monitor0 (Generic PnP Monitor)
[01/12/2022 02:35:53.486] [15] [RefreshRateFeature.cs#34:GetAllStatesAsync] Current built in display settings: {Width=2560, Height=1440} Progressive 60hz @ Depth32Bit @ {X=0,Y=0}
[01/12/2022 02:35:53.517] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=DiscreteGPUControl]
[01/12/2022 02:35:53.543] [15] [RefreshRateFeature.cs#53:GetAllStatesAsync] Possible refresh rates are LenovoLegionToolkit.Lib.RefreshRate, LenovoLegionToolkit.Lib.RefreshRate
[01/12/2022 02:35:53.545] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=TouchpadLockControl]
[01/12/2022 02:35:53.546] [21] [HDRFeature.cs#27:IsSupportedAsync] HDR support: False
[01/12/2022 02:35:53.552] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=FnLockControl]
[01/12/2022 02:35:53.555] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=FnLockFeature]
[01/12/2022 02:35:53.558] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=WinKeyControl]
[01/12/2022 02:35:53.558] [34] [AbstractDriverFeature.cs#48:GetStateAsync] State is On [feature=FnLockFeature]
[01/12/2022 02:35:53.566] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=FlipToStartControl]
[01/12/2022 02:35:53.570] [34] [AbstractUEFIFeature.cs#47:ReadFromUefiAsync] Reading from UEFI... [feature=FlipToStartFeature]
[01/12/2022 02:35:53.573] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=OverDriveControl]
[01/12/2022 02:35:53.575] [34] [AbstractUEFIFeature.cs#67:ReadFromUefiAsync] Read from UEFI successful [feature=FlipToStartFeature]
[01/12/2022 02:35:53.587] [34] [AbstractDriverFeature.cs#81:SendCodeAsync] DeviceIoControl returned 0, last error: 31 [feature=WhiteKeyboardBacklightFeature]
[01/12/2022 02:35:53.589] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=PowerModeFeature]
[01/12/2022 02:35:53.601] [21] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Quiet [feature=PowerModeFeature]
[01/12/2022 02:35:53.606] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=BatteryFeature]
[01/12/2022 02:35:53.606] [34] [AbstractDriverFeature.cs#48:GetStateAsync] State is Normal [feature=BatteryFeature]
[01/12/2022 02:35:53.607] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=AlwaysOnUSBFeature]
[01/12/2022 02:35:53.608] [34] [AbstractDriverFeature.cs#48:GetStateAsync] State is OnAlways [feature=AlwaysOnUSBFeature]
[01/12/2022 02:35:53.610] [1] [HybridModeFeature.cs#32:GetStateAsync] Getting state...
[01/12/2022 02:35:53.611] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=GSyncFeature]
[01/12/2022 02:35:53.618] [1] [RefreshRateFeature.cs#61:GetStateAsync] Getting current refresh rate...
[01/12/2022 02:35:53.618] [1] [DisplayExtensions.cs#20:GetBuiltInDisplayAsync] Found displays:
[01/12/2022 02:35:53.619] [1] [DisplayExtensions.cs#22:GetBuiltInDisplayAsync]  - Display: \\.\DISPLAY1\Monitor0 (Generic PnP Monitor)
[01/12/2022 02:35:53.623] [21] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is On [feature=GSyncFeature]
[01/12/2022 02:35:53.629] [1] [AbstractDriverFeature.cs#41:GetStateAsync] Getting state... [feature=FnLockFeature]
[01/12/2022 02:35:53.629] [34] [AbstractDriverFeature.cs#48:GetStateAsync] State is On [feature=FnLockFeature]
[01/12/2022 02:35:53.630] [21] [RefreshRateFeature.cs#76:GetStateAsync] Current refresh rate is LenovoLegionToolkit.Lib.RefreshRate [currentSettings={Width=2560, Height=1440} Progressive 60hz @ Depth32Bit @ {X=0,Y=0}]
[01/12/2022 02:35:53.631] [15] [HybridModeFeature.cs#43:GetStateAsync] State is On [gsync=On, igpuMode=Default]
[01/12/2022 02:35:53.631] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=TouchpadLockFeature]
[01/12/2022 02:35:53.638] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=WinKeyFeature]
[01/12/2022 02:35:53.643] [15] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Off [feature=TouchpadLockFeature]
[01/12/2022 02:35:53.645] [34] [AbstractUEFIFeature.cs#47:ReadFromUefiAsync] Reading from UEFI... [feature=FlipToStartFeature]
[01/12/2022 02:35:53.646] [34] [AbstractUEFIFeature.cs#67:ReadFromUefiAsync] Read from UEFI successful [feature=FlipToStartFeature]
[01/12/2022 02:35:53.648] [1] [AbstractLenovoGamezoneWmiFeature.cs#60:GetStateAsync] Getting state... [feature=OverDriveFeature]
[01/12/2022 02:35:53.651] [15] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Off [feature=WinKeyFeature]
[01/12/2022 02:35:53.660] [15] [AbstractLenovoGamezoneWmiFeature.cs#70:GetStateAsync] State is Off [feature=OverDriveFeature]
[01/12/2022 02:35:53.665] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=PowerModeControl]
[01/12/2022 02:35:53.666] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=BatteryModeControl]
[01/12/2022 02:35:53.666] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=AlwaysOnUSBControl]
[01/12/2022 02:35:53.666] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=ToggleHybridModeControl]
[01/12/2022 02:35:53.666] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=RefreshRateControl]
[01/12/2022 02:35:53.667] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=HDRControl]
[01/12/2022 02:35:53.667] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=DiscreteGPUControl]
[01/12/2022 02:35:53.671] [1] [GPUController.cs#106:StopAsync] Stopping... [refreshTask.isNull=True, _refreshCancellationTokenSource.IsCancellationRequested=]
[01/12/2022 02:35:53.672] [1] [GPUController.cs#113:StopAsync] Waiting to finish...
[01/12/2022 02:35:53.672] [1] [GPUController.cs#125:StopAsync] Finished
[01/12/2022 02:35:53.672] [1] [GPUController.cs#132:StopAsync] Stopped
[01/12/2022 02:35:53.673] [1] [GPUController.cs#96:StartAsync] Starting... [delay=1000, interval=5000]
[01/12/2022 02:35:53.674] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=TouchpadLockControl]
[01/12/2022 02:35:53.674] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=FnLockControl]
[01/12/2022 02:35:53.675] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=WinKeyControl]
[01/12/2022 02:35:53.675] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=FlipToStartControl]
[01/12/2022 02:35:53.675] [1] [AbstractRefreshingControl.cs#49:RefreshAsync] Refreshing control... [feature=OverDriveControl]
[01/12/2022 02:35:53.678] [34] [GPUController.cs#186:RefreshLoopAsync] Initializing NVAPI...
[01/12/2022 02:35:53.679] [34] [GPUController.cs#191:RefreshLoopAsync] Initialized NVAPI
[01/12/2022 02:35:53.752] [1] [AbstractRefreshingControl.cs#66:RefreshAsync] Exception when refreshing control. [feature=HDRControl]
=== Exception ===
System.NotSupportedException: Specified method is not supported.
   at LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl`1.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.Dashboard.HDRControl.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

=== Exception demystified ===
System.NotSupportedException: Specified method is not supported.
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl<T>.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.Dashboard.HDRControl.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

[01/12/2022 02:35:54.045] [1] [AbstractRefreshingControl.cs#66:RefreshAsync] Exception when refreshing control. [feature=HDRControl]
=== Exception ===
System.NotSupportedException: Specified method is not supported.
   at LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl`1.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.Dashboard.HDRControl.OnRefreshAsync()
   at LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

=== Exception demystified ===
System.NotSupportedException: Specified method is not supported.
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractToggleFeatureCardControl<T>.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.Dashboard.HDRControl.OnRefreshAsync()
   at async Task LenovoLegionToolkit.WPF.Controls.AbstractRefreshingControl.RefreshAsync()

[01/12/2022 02:35:54.680] [9] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:35:54.682] [9] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:35:55.239] [9] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:35:55.239] [9] [GPUController.cs#209:RefreshLoopAsync] Refreshed
[01/12/2022 02:35:56.638] [5] [UpdateChecker.cs#53:Check] Checked [updates.Length=0]
[01/12/2022 02:36:00.244] [23] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:36:00.244] [23] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:36:00.259] [23] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:36:00.260] [23] [GPUController.cs#209:RefreshLoopAsync] Refreshed
[01/12/2022 02:36:05.261] [9] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:36:05.262] [9] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:36:05.267] [9] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:36:05.267] [9] [GPUController.cs#209:RefreshLoopAsync] Refreshed
[01/12/2022 02:36:10.273] [23] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:36:10.273] [23] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:36:10.277] [23] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:36:10.278] [23] [GPUController.cs#209:RefreshLoopAsync] Refreshed
[01/12/2022 02:36:15.279] [34] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:36:15.279] [34] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:36:15.294] [34] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:36:15.294] [34] [GPUController.cs#209:RefreshLoopAsync] Refreshed
[01/12/2022 02:36:20.296] [34] [GPUController.cs#203:RefreshLoopAsync] Will refresh...
[01/12/2022 02:36:20.296] [34] [GPUController.cs#242:RefreshStateAsync] Refresh in progress...
[01/12/2022 02:36:20.301] [34] [GPUController.cs#286:RefreshStateAsync] GPU inactive [status=Inactive, processes.Count=0, gpuInstanceId=]
[01/12/2022 02:36:20.302] [34] [GPUController.cs#209:RefreshLoopAsync] Refreshed
```
</details>

### Do you have Lenovo software installed?

- [X] Lenovo Vantage is installed
- [X] Lenovo Hotkeys is installed
- [ ] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

Vantage won't let me change the keyboard either, maybe it's related, but please help me out :(

**Comment by BartoszCichecki** [comment]
As stated in the readme, LLT does not support iCue keyboards.

**Comment by sebolio** [comment]
what do you mean by "icue keyboard"?

**Comment by BartoszCichecki** [comment]
I mean that Keyboards that were put in Legion 7 and Slim 7 gen6 are keyboards that are using Corsair's iCue, which is not supported in LLT. Only white-backlight, 4-zone RGB and Spectrum RGB (currently only in Legion 7 and Slim 7 from 2022) are supported.

There was a discussion about it here: https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/178#issuecomment-1323980789
