### ISSUE TITLE
System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by TuanZiGit** [BartoszCichecki/LenovoLegionToolkit#744]
### Version

0.0.1 Beta Build 20230526105125 (Github Action)

### OS

Windows 11 Canary 22H2 25350

### Device

GeekPro G5000 IRH8

### BIOS version

LZCN23WW

### What's wrong?

When I using my computer and the error pops up and LLT crashed.

### How to reproduce the bug?

idk how i make that

### What is the behavior that you expected?

normally executing...

### Logs

```=== Exception ===
System.ComponentModel.Win32Exception (87): 参数错误。
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdatePeer(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.ComponentModel.Win32Exception: 参数错误。
   at int MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, out StringBuilder lpString, int nMaxCount)
   at string System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at void System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at object System.Windows.Automation.Peers.AutomationPeer.UpdatePeer(object arg)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)

[27/05/2023 02:33:38.108] [1] [NotificationsManager.cs#36:OnNotificationReceived] Notification Type: CapsLockOff, Duration: Short, Args: [] received
[27/05/2023 02:33:38.130] [1] [NotificationsManager.cs#222:OnNotificationReceived] Notification Type: CapsLockOff, Duration: Short, Args: [] shown.
[27/05/2023 02:33:39.522] [1] [NotificationsManager.cs#36:OnNotificationReceived] Notification Type: CapsLockOn, Duration: Short, Args: [] received
[27/05/2023 02:33:39.544] [1] [NotificationsManager.cs#222:OnNotificationReceived] Notification Type: CapsLockOn, Duration: Short, Args: [] shown.
[27/05/2023 02:33:40.206] [1] [NotificationsManager.cs#36:OnNotificationReceived] Notification Type: CapsLockOff, Duration: Short, Args: [] received
[27/05/2023 02:33:40.246] [1] [NotificationsManager.cs#222:OnNotificationReceived] Notification Type: CapsLockOff, Duration: Short, Args: [] shown.
[27/05/2023 02:33:49.909] [1] [App.xaml.cs#181:AppDomain_UnhandledException] Unhandled exception occurred.
=== Exception ===
System.ComponentModel.Win32Exception (87): 参数错误。
   at MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, StringBuilder lpString, Int32 nMaxCount)
   at System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdatePeer(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LenovoLegionToolkit.WPF.App.Main()

=== Exception demystified ===
System.ComponentModel.Win32Exception: 参数错误。
   at int MS.Win32.UnsafeNativeMethods.GetWindowText(HandleRef hWnd, out StringBuilder lpString, int nMaxCount)
   at string System.Windows.Automation.Peers.WindowAutomationPeer.GetNameCore()
   at void System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at object System.Windows.Automation.Peers.AutomationPeer.UpdatePeer(object arg)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at void System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at void MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at void MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at void System.Windows.Threading.DispatcherOperation.Invoke()
   at void System.Windows.Threading.Dispatcher.ProcessQueue()
   at IntPtr System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at IntPtr MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at object MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at object System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at IntPtr MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at IntPtr MS.Win32.UnsafeNativeMethods.DispatchMessage(in MSG msg)
   at void System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.Run()
   at object System.Windows.Application.RunDispatcher(object ignore)
   at int System.Windows.Application.RunInternal(Window window)
   at int System.Windows.Application.Run()
   at void LenovoLegionToolkit.WPF.App.Main()

[27/05/2023 02:33:49.954] [1] [MainWindow.xaml.cs#110:MainWindow_Closing] Minimizing...

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [ ] Lenovo Vantage
- [ ] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

### Additional information

_No response_

**Comment by BartoszCichecki** [comment]
This looks like an issue in Windows. You are using a Canary build of Windows, so that is most likely the issue.
