### ISSUE TITLE
Latest update stopped working for me

### ISSUE THREAD

**Issue by bogdan-d** [BartoszCichecki/LenovoLegionToolkit#887]
### Rules

- [X] I made myself familiar with the README.
- [X] I checked closed issues for similar ones and did not find a similar problem mentioned before.
- [X] I understand that, if insufficient information was provided, my issue will be closed without an answer.

### Version

2.15.2

### OS

Windows 10 Pro 22H2 build 19045.3208 Windows Feature Experience Pack 1000.19041.1000.0

### Device

Legion 5 Pro 16ITH6H

### BIOS version

H1CN53WW

### What's wrong?

I updated Lenovo Legion Toolkit to the latest version and now some errors pop-up saying that some feature is not supported, and the exits.

### How to reproduce the bug?

I think it is system/OS dependent.

### What is the behavior that you expected?

To work

### Logs

error_2023_07_18_12_53_08.txt

```text
Application_DispatcherUnhandledException
=== Exception ===
System.InvalidOperationException: No supported feature found. [type=DGPUNotify
   at LenovoLegionToolkit.Lib.Features.Hybrid.Notify.DGPUNotify.NotifyAsync(Boolean publish)
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Exception demystified ===
System.InvalidOperationException: No supported feature found. [type=DGPUNotify
   at async Task LenovoLegionToolkit.Lib.Features.Hybrid.Notify.DGPUNotify.NotifyAsync(bool publish)
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
```

error_2023_07_18_12_53_32.txtr

```text
AppDomain_UnhandledException
=== Exception ===
System.InvalidOperationException: No supported feature found. [type=DGPUNotify
   at LenovoLegionToolkit.Lib.Features.Hybrid.Notify.DGPUNotify.NotifyAsync(Boolean publish)
   at LenovoLegionToolkit.WPF.App.Application_Startup(Object sender, StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at LenovoLegionToolkit.WPF.App.Main()

=== Exception demystified ===
System.InvalidOperationException: No supported feature found. [type=DGPUNotify
   at async Task LenovoLegionToolkit.Lib.Features.Hybrid.Notify.DGPUNotify.NotifyAsync(bool publish)
   at async void LenovoLegionToolkit.WPF.App.Application_Startup(object sender, StartupEventArgs e)
   at void System.Threading.Tasks.Task.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at void System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at void System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(object state)
   at void MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(object obj)
   at void MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
   at void System.Windows.Threading.DispatcherOperation.Invoke()
   at void System.Windows.Threading.Dispatcher.ProcessQueue()
   at IntPtr System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at IntPtr MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
   at object MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
   at object System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
   at object System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
   at object System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
   at IntPtr MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
   at IntPtr MS.Win32.UnsafeNativeMethods.DispatchMessage(in MSG msg)
   at void System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at void System.Windows.Threading.Dispatcher.Run()
   at object System.Windows.Application.RunDispatcher(object ignore)
   at int System.Windows.Application.RunInternal(Window window)
   at int System.Windows.Application.Run()
   at void LenovoLegionToolkit.WPF.App.Main()
```

### Additional information

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/4302588/847efc93-32d2-4c95-b69b-f0301b07dc50)

![image](https://github.com/BartoszCichecki/LenovoLegionToolkit/assets/4302588/f4ef8cfd-4cd4-46a4-9332-49edd9ff426e)

**Comment by DevNightshade** [comment]
check comments of https://github.com/BartoszCichecki/LenovoLegionToolkit/issues/886

**Comment by BartoszCichecki** [comment]
Duplicate of #886

**Comment by bogdan-d** [comment]
> check comments of #886

yeah, the previous thread was not available when I started posting mine, thanks.
